version: '3.8'

services:
  accesslink-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accesslink-lgbtq-website
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    networks:
      - accesslink-network
    labels:
      - "com.docker.compose.service=accesslink-website"
      - "description=AccessLink LGBTQ+ Website"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  accesslink-network:
    driver: bridge
    name: accesslink-network

# Optional: Add volumes for logs if needed
# volumes:
#   nginx_logs:
#     driver: local
